SCENARIOS = "data/scenarios.yaml"
SCENARIOS_DATA = "data/scenario_data.yaml"
GENERATED_CLUES = "generated_clues"
GENERATED_CLUE_GUESSES = "data/guesses.yaml"
GENERATED_CLUES_NOTES = "generated_clues/notes"